# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - small_controller
    - big_controller

  small_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - small_joint_1
      - small_joint_2
      - small_joint_3
      - small_joint_4
      - small_joint_5
      - small_joint_6

  big_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - big_joint_1
      - big_joint_2
      - big_joint_3
      - big_joint_4
      - big_joint_5
      - big_joint_6